### PR TITLE
Improves layout of readme

### PR DESCRIPTION
**Pull request by matthewdking**
relates #3

Set up structure for weeks research to be added by the students.
I figure if we set this up and then open a new issue for week 1 to ask the students to upload the research?

### CODE REVIEW

**Review by veredrec — APPROVED** [review]
I like the idea and the way it is structured :100:

**Comment by veredrec** [comment]
@matthewdking my only suggestion is that for week-1 we won't ask the student to create a README file but to upload what they have as findings from their research.

**Comment by matthewdking** [comment]
@veredrec what is the difference between a README and their findings?

**Comment by veredrec** [comment]
@matthewdking I meant that if the teams didn't write a README for this week, they can add the files they have, even if they're not md files (e.g. javascript).

**Comment by matthewdking** [comment]
@veredrec oh right I see! Yeah makes sense they can just upload what they want for week 1 but I think from week 2 they should be creating a markdown file with their research in.

**Comment by veredrec** [comment]
@matthewdking :+1:

**Review by shiryz — APPROVED** [review]

**Pull request merged**
